version: '3.4'
services:
  # server:
  #   extends:
  #     file: common-services.yml
  #     service: base_node
  #   build:
  #     context: ./
  #     dockerfile: dockerfile-node
  #   command: 'node server.js'
  #   ports:
  #     - ${API_PORT}:3300
  #   restart: always
   
  mongodb:
    image: mongo
    container_name: "mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - './mongodb:/data/db'
    ports:
      - ${MONGO_PORT}:27017
  # rabbitmq:
  #   image: rabbitmq:3.8.0-management
  #   hostname: crawlers-rabbitmq
  #   ports:
  #     - 1${RABBITMQ_PORT}:15672
  #     - ${RABBITMQ_PORT}:5672
  #   expose:
  #     - 1${RABBITMQ_PORT}
  #   restart: always
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
  #     - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}

  